INSERT INTO questions (lang, question, real_answer, fake_answers, citation) VALUES
('en', 'The world''s largest $blank$ is located in Malaysia.', 'roundabout', ARRAY['shopping mall', 'water park', 'swimming pool', 'parking lot'], 'Putrajaya Roundabout, Malaysia'),
('en', 'In 1932, Australia fought and lost a war against $blank$.', 'emus', ARRAY['kangaroos', 'rabbits', 'cassowaries', 'koalas'], 'Great Emu War of 1932'),
('en', 'The shortest war in history lasted $blank$ minutes.', '38', ARRAY['12', '55', '90', '3'], 'Anglo-Zanzibar War, 1896'),
('en', 'Honey never $blank$, even after thousands of years.', 'spoils', ARRAY['crystallizes', 'changes color', 'loses sweetness', 'evaporates'], 'Edible honey found in Egyptian tombs'),
('en', 'A group of flamingos is called a $blank$.', 'flamboyance', ARRAY['flock', 'parade', 'colony', 'pinkness'], 'Collective nouns for animals'),
('en', 'The inventor of the Pringles can is buried in a $blank$.', 'pringles can', ARRAY['coffin shaped like a chip', 'gold casket', 'cardboard tube', 'potato sack'], 'Fredric Baur, inventor of the Pringles can'),
('en', 'Octopuses have $blank$ hearts.', 'three', ARRAY['two', 'four', 'five', 'one'], 'Marine biology'),
('en', 'The national animal of Scotland is the $blank$.', 'unicorn', ARRAY['highland cow', 'red deer', 'golden eagle', 'thistle'], 'Scottish heraldry'),
('en', 'In Switzerland, it is illegal to own just one $blank$.', 'guinea pig', ARRAY['goldfish', 'hamster', 'rabbit', 'parrot'], 'Swiss animal welfare laws'),
('en', 'Bananas are technically classified as $blank$.', 'berries', ARRAY['herbs', 'vegetables', 'grasses', 'nuts'], 'Botanical classification'),
('en', 'The longest hiccupping spree lasted $blank$ years.', '68', ARRAY['12', '25', '43', '7'], 'Charles Osborne, 1922-1990'),
('en', 'Cleopatra lived closer in time to the $blank$ than to the building of the Great Pyramid.', 'moon landing', ARRAY['fall of Rome', 'invention of printing', 'discovery of America', 'birth of Jesus'], 'Historical timelines'),
('en', 'A jiffy is an actual unit of time equal to $blank$.', '1/100th of a second', ARRAY['1 millisecond', '1/10th of a second', '1 nanosecond', '1/1000th of a second'], 'Physics terminology'),
('en', 'The total weight of all ants on Earth is roughly equal to the total weight of all $blank$.', 'humans', ARRAY['elephants', 'whales', 'dogs', 'birds'], 'Entomology estimates'),
('en', 'Nintendo was originally a $blank$ company.', 'playing card', ARRAY['toy robot', 'fishing equipment', 'candy', 'bicycle'], 'Nintendo founded 1889'),
('en', 'The dot over the letters i and j is called a $blank$.', 'tittle', ARRAY['pip', 'jot', 'speck', 'nib'], 'Typography terminology'),
('en', 'Astronauts on the ISS see $blank$ sunrises every day.', '16', ARRAY['6', '24', '12', '8'], 'ISS orbital period of 90 minutes'),
('en', 'Oxford University is older than the $blank$ Empire.', 'Aztec', ARRAY['Roman', 'British', 'Ottoman', 'Mongol'], 'Oxford teaching from 1096, Aztec founded 1325'),
('en', 'The inventor of the fire hydrant is unknown because the patent was $blank$.', 'destroyed in a fire', ARRAY['lost at sea', 'stolen', 'never filed', 'eaten by rats'], 'US Patent Office fire of 1836'),
('en', 'There are more possible iterations of a game of $blank$ than atoms in the observable universe.', 'chess', ARRAY['checkers', 'go', 'monopoly', 'risk'], 'Shannon number');
